[project]
name = "convert-to-markdown"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "markitdown>=0.0.1a4",
    "openai>=1.64.0",
    "python-dotenv>=1.0.1",
    "uv>=0.6.3",
]
